version: '3.8'

services:
  app:
    build: . 
    container_name: my_app
    ports:
      - "8085:80" 
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db_API
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: API_DB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    platform: linux/amd64
    container_name: API_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge